### ISSUE TITLE
Example to implement and use ITranscoderListener

### ISSUE THREAD

**Issue by andresgutice** [fantacode/TranscoderXamarin#1]
Hello, thank you very much for this great library, I would like how to implement and use ITranscoderListener for the use of the Transcoder

```
var source = new FilePathDataSource(videoInput.FileInfo.FullName);

var clip = new ClipDataSource(source, 
Convert.ToInt32(videoFormat.StartVideo.TotalMilliseconds) * 1000, 
Convert.ToInt32(videoFormat.EndVideo.TotalMilliseconds) * 1000);

var transcoder = Transcoder.Into(fileInfo.AbsolutePath)
                    .SetListener(**listenerimplementation **)
                    .AddDataSource(clip)
                    .Transcode();
```

Thank you very much for your attention

**Comment by muhaym** [comment]
![image](https://user-images.githubusercontent.com/10905479/80327519-01643500-885a-11ea-84b6-fcb9456a3bb4.png)

In the class you are consuming Transcoder, Implement interface 
`Java.Lang.Object, ITranscoderListener`

![image](https://user-images.githubusercontent.com/10905479/80327530-0aed9d00-885a-11ea-98bd-1c3dc39767f2.png)

And in SetListener, Use
`SetListener(this)`

**Comment by andresgutice** [comment]
Thank you very much for your answer, it has helped me.

I have another problem, and that is when I try to use the Transcoder I get this exception

`{Java.Lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics; ---> Java.Lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.companyname.videocompress-nKaNSHoCpDp8QwFFiL3-HQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.videocompress-nKaNSHoCpDp8QwFFiL3-HQ==/lib/arm, /data/app/com.companyname.videocompress-nKaNSHoCpDp8QwFFiL3-HQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
   --- End of inner exception stack trace ---
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at com.otaliastudios.opengl.core.EglCore.<init>(Unknown Source:2)
	at com.otaliastudios.transcoder.transcode.internal.VideoEncoderInput.<init>(VideoEncoderInput.java:35)
	at com.otaliastudios.transcoder.transcode.VideoTrackTranscoder.onStartEncoder(VideoTrackTranscoder.java:79)
	at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:64)
	at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:194)
	at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:223)
	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:371)
	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.companyname.videocompress-nKaNSHoCpDp8QwFFiL3-HQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.videocompress-nKaNSHoCpDp8QwFFiL3-HQ==/lib/arm, /data/app/com.companyname.videocompress-nKaNSHoCpDp8QwFFiL3-HQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 13 more
}`

As you could see in my previous code, I am trying to trim the video...

I don't know what happens, I hope you can help me, I wish you the best and thank you very much

**Comment by muhaym** [comment]
https://github.com/fantacode/TranscoderXamarin#installation

Install https://www.nuget.org/packages/Xamarin.Kotlin.StdLib.Jdk7/

**Comment by andresgutice** [comment]
Thank you very much friend, it has worked wonders for me, I will continue testing the library
